name: macos
on: [push, pull_request]
jobs:
  build:
    runs-on: macos-11
    steps:
      - uses: actions/checkout@v2
      - name: Build
        run: |
          /bin/bash --login
          mkdir Build
          cd Build
          ccmake ..
          make
