name: macos
on: [push, pull_request]
jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build
        run: |
          brew update;
          mkdir Build
          cd Build
          ccmake ..
          make
