name: macos
on: [push, pull_request]
jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build
        shell: bash
        run: |
          export TERM=xterm-256color
          mkdir Build
          cd Build
          cmake ..
          make
