name: macos
on: [push, pull_request]
jobs:
  build-macos-monterey:
    runs-on: macos-12
    steps:
      - uses: actions/checkout@v2
      - name: Build
        shell: bash
        run: |
          export TERM=xterm-256color
          mkdir Build
          cd Build
          cmake ..
          make -j
  build-macos-big-sur:
    runs-on: macos-11
    steps:
      - uses: actions/checkout@v2
      - name: Build
        shell: bash
        run: |
          export TERM=xterm-256color
          mkdir Build
          cd Build
          cmake ..
          make -j
  build-macos-catalina:
    runs-on: macos-10.15
    steps:
      - uses: actions/checkout@v2
      - name: Build
        shell: bash
        run: |
          export TERM=xterm-256color
          mkdir Build
          cd Build
          cmake ..
          make -j
  build-ubuntu-22:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        shell: bash
        run: sudo apt-get install libglu1-mesa-dev libxt-dev libxi-dev libglew-dev libxmu-dev
      - name: Build
        shell: bash
        run: |
          export TERM=xterm-256color
          mkdir Build
          cd Build
          cmake ..
          make -j
  build-ubuntu-20:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        shell: bash
        run: sudo apt-get install libglu1-mesa-dev libxt-dev libxi-dev libglew-dev libxmu-dev
      - name: Build
        shell: bash
        run: |
          export TERM=xterm-256color
          mkdir Build
          cd Build
          cmake ..
          make -j
  build-ubuntu-18:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        shell: bash
        run: sudo apt-get install libglu1-mesa-dev libxt-dev libxi-dev libglew-dev libxmu-dev
      - name: Build
        shell: bash
        run: |
          export TERM=xterm-256color
          mkdir Build
          cd Build
          cmake ..
          make -j
  build-windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build
        shell: bash
        run: |
          export TERM=xterm-256color
          mkdir Build
          cd Build
          cmake ..
          make -j
